# Generated by Django 4.2.3 on 2023-09-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('schoolName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('principal', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentName', models.CharField(max_length=100)),
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
